url: https://galah.ala.org.au
template:
  bootstrap: 5
  bslib:
    code_font: {google: "Source Code Pro"}
  params:
    bootswatch: cerulean
navbar:
  structure:
    left:
    - home
    - quickstart
    - articles
    - reference
    right:
    - news
    - github
  components:
    quickstart:
      text: Quick start guide
      href: articles/quick_start_guide.html
    articles:
      text: Articles
      menu:
      - text: Choosing an atlas
        href: articles/choosing_an_atlas.html
      - text: Piping in galah
        href: articles/piping.html
      - text: Look up information
        href: articles/look_up_information.html
      - text: Narrow your results
        href: articles/narrow_your_results.html
      - text: Download data
        href: articles/download_data.html
    news:
      text: News
      href: news/index.html
reference:
- title: Start a data query
  contents: galah_call
- title: Look up information
  contents:
  - show_all
  - search_all
  - search_taxa
  - search_identifiers
  - search_fields
  - search_media
  - search_values
  - show_all_profiles
  - show_all_fields
  - show_all_atlases
  - show_all_reasons
  - show_all_ranks
  - show_values
- title: Narrow results
  contents:
  - galah_identify
  - galah_filter
  - galah_select
  - galah_group_by
  - galah_geolocate
  - galah_apply_profile
  - galah_down_to
- title: Download data
  contents:
  - atlas_occurrences
  - atlas_counts
  - atlas_species
  - atlas_taxonomy
  - atlas_media
  - collect_media
  - collect_occurrences
- title: Masked functions
  contents:
  - identify.data_request
  - filter.data_request
  - select.data_request
  - group_by.data_request
  - st_crop.data_request
  - slice_head.data_request
  - count.data_request
  - reexports
- title: Manage cache
  contents:
  - clear_cached_files
- title: Configure session
  contents: galah_config
- title: Cite
  contents: atlas_citation



# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
