---
title: "02 Narrow your results"
author: "Martin Westgate & Dax Kellie"
date: "20/12/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
vignette: >
  %\VignetteIndexEntry{02 Narrow your results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
Each occurrence record contains taxonomic information and 
information about the observation itself, like its location and the date
of observation. These pieces of information are recorded and categorised into 
respective **fields**. When you import data using `galah`, columns of the 
resulting `tibble` correspond to these fields.

Data fields are important because they provide a means to manipulate queries
to return only the information that you need, and no more. Consequently, much of 
the architecture of `galah` has been designed to make narrowing as simple as possible. 
These functions include:

-   `search_taxa`
-   `galah_filter`
-   `galah_select`
-   `galah_group_by`
-   `galah_geolocate`
-   `galah_down_to`

These names have been chosen to echo comparable functions from `dplyr`; namely
`filter`, `select` and `group_by`. With the exception of `galah_geolocate`, they
also use `dplyr` tidy evaluation and syntax. This means that the 
way you use `dplyr` functions is also how you use `galah_` functions.

# search_taxa
Perhaps unsurprisingly, `search_taxa`searches for taxonomic information. 
It uses fuzzy matching to work a lot like the search bar on the 
[Atlas of Living Australia website](https://bie-ws.ala.org.au/), 
and you can use it to search for taxa by their scientific name. Finding your 
desired taxon with `search_taxa` is an important step to using this taxonomic 
information to download  data with `galah`.  
  
For example, to search for reptiles, we first need to identify whether we have 
the correct query:


```r
search_taxa("Reptilia")
```

```
## # A tibble: 1 × 9
##   search_term scientific_name taxon_concept_id                                 rank  match_type kingdom  phylum  class  issues
##   <chr>       <chr>           <chr>                                            <chr> <chr>      <chr>    <chr>   <chr>  <chr> 
## 1 Reptilia    REPTILIA        urn:lsid:biodiversity.org.au:afd.taxon:682e1228… class exactMatch Animalia Chorda… Repti… noIss…
```

If we want to be more specific by providing additional taxonomic information
to `search_taxa`, you can provide a `data.frame` containing more levels of the
taxonomic hierarchy:

```r
search_taxa(data.frame(genus = "Eolophus", kingdom = "Aves"))
```

```
## # A tibble: 1 × 13
##   search_term   scientific_name scientific_name_… taxon_concept_id    rank  match_type kingdom phylum class order family genus
##   <chr>         <chr>           <chr>             <chr>               <chr> <chr>      <chr>   <chr>  <chr> <chr> <chr>  <chr>
## 1 Eolophus_Aves Eolophus        Bonaparte, 1854   urn:lsid:biodivers… genus exactMatch Animal… Chord… Aves  Psit… Cacat… Eolo…
## # … with 1 more variable: issues <chr>
```

# galah_filter
Perhaps the most important function in `galah` is `galah_filter`, which is used
to filter the rows of queries:


```r
# Get total record count since 2000
galah_call() |>
  galah_filter(year > 2000) |>
  atlas_counts()
```

```
## # A tibble: 1 × 1
##      count
##      <int>
## 1 62834053
```

```r
# Get total record count for iNaturalist in 2021
galah_call() |>
  galah_filter(
    year > 2000,
    dataResourceName == "iNaturalist Australia"
  ) |>
  atlas_counts()
```

```
## # A tibble: 1 × 1
##     count
##     <int>
## 1 2647108
```

To find available fields and corresponding valid values, use the field lookup 
functions `show_all_fields`, `search_fields` and `find_field_values`.  

A further notable feature of `galah_filter` is the ability to specify a `profile` to 
remove records that are suspect in some way. 


```r
galah_call() |>
  galah_filter(year > 2000, profile = "ALA") |>
  atlas_counts()
```

```
## # A tibble: 1 × 1
##      count
##      <int>
## 1 55520901
```

To see a full list of data quality profiles, use `show_all_profiles()`.

Finally, a special case of `galah_filter` is to make more complex taxonomic
queries than are possible using `search_taxa`. By using the `taxonConceptID` 
field, it is possible to build queries that exclude certain taxa, for example.
This can be useful for paraphyletic concepts such as invertebrates:


```r
galah_call() |>
  galah_filter(
     taxonConceptID == search_taxa("Animalia")$taxon_concept_id,
     taxonConceptID != search_taxa("Chordata")$taxon_concept_id
  ) |>
  galah_group_by(class) |>
  atlas_counts()
```

```
## # A tibble: 83 × 2
##    class          count
##    <chr>          <int>
##  1 Insecta      3307548
##  2 Gastropoda    837104
##  3 Arachnida     525840
##  4 Malacostraca  515797
##  5 Maxillopoda   462743
##  6 Polychaeta    256905
##  7 Bivalvia      206137
##  8 Anthozoa      163329
##  9 Demospongiae  107498
## 10 Ostracoda      56295
## # … with 73 more rows
```

# galah_group_by
Use `galah_group_by` to group record counts and summarise counts by specified fields:


```r
# Get record counts since 2010, grouped by year and basis of record
galah_call() |>
  galah_filter(year > 2015 & year <= 2020) |>
  galah_group_by(year, basisOfRecord) |>
  atlas_counts()
```

```
## # A tibble: 35 × 3
##    year  basisOfRecord         count
##    <chr> <chr>                 <int>
##  1 2020  HUMAN_OBSERVATION   5820506
##  2 2020  PRESERVED_SPECIMEN    13637
##  3 2020  OBSERVATION            2863
##  4 2020  UNKNOWN                 365
##  5 2020  MATERIAL_SAMPLE         250
##  6 2020  LIVING_SPECIMEN         127
##  7 2020  MACHINE_OBSERVATION      37
##  8 2019  HUMAN_OBSERVATION   5399921
##  9 2019  UNKNOWN               51747
## 10 2019  PRESERVED_SPECIMEN    38117
## # … with 25 more rows
```

# galah_select
Use `galah_select` to choose which columns are returned when downloading records:


```r
# Get records from 1930, but only 'eventDate' and 'kingdom' columns
galah_call() |>
  galah_filter(year == 1930) |>
  galah_select(eventDate, kingdom) |>
  atlas_occurrences()
```

# galah_geolocate
Use `galah_geolocate` to specify a geographic area or region to limit your search:


```r
# Get list of perameles species only in area specified:
# (Note: This can also be specified by a shapefile)
wkt <- "POLYGON((131.36328125 -22.506468769126,135.23046875 -23.396716654542,134.17578125 -27.287832521411,127.40820312499 -26.661206402316,128.111328125 -21.037340349154,131.36328125 -22.506468769126))"

galah_call() |>
  search_taxa("perameles") |>
  galah_geolocate(wkt) |>
  atlas_species()
```

# galah_down_to
Use `galah_down_to` to specify the lowest taxonomic level to contruct a taxonomic 
tree:


```r
galah_call() |>
  search_taxa("fungi") |>
  galah_down_to(phylum) |>
  atlas_taxonomy()
```
