---
title: "Revamped syntax in galah 1.4.0"
author: "Dax Kellie"
date: "20/12/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
vignette: >
  %\VignetteIndexEntry{Syntax Changes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`galah` 1.4.0 implements new, revised syntax for function names. These new 
function names are intended to improve users' ability to know what each function 
does and what output they can expect. <br>

First, let's have a look at all the changes, then go through each major syntax 
change one-by-one.

<table class="table lightable-paper" style='width: auto !important; margin-left: auto; margin-right: auto; font-family: "Arial Narrow", arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;'>
 <thead>
  <tr>
   <th style="text-align:left;"> galah 1.3.1 and earlier </th>
   <th style="text-align:left;"> galah 1.4.0 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> ala_counts </td>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> atlas_counts </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> ala_occurrences </td>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> atlas_occurrences </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> ala_species </td>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> atlas_species </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> ala_media </td>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> atlas_media </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> ala_taxonomy </td>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> atlas_taxonomy </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> ala_citation </td>
   <td style="text-align:left;font-weight: bold;color: #E06E53 !important;"> atlas_citation </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> select_filters </td>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> galah_filter </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> select_columns </td>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> galah_select </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> select_locations </td>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> galah_geolocate </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;">  </td>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> galah_group_by </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;">  </td>
   <td style="text-align:left;font-weight: bold;color: #c7902a !important;"> galah_down_to </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> select_taxa </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> search_taxa </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> search_fields </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> search_fields </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;">  </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> show_all_fields </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> find_profiles </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> show_all_profiles </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> find_ranks </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> show_all_ranks </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> find_atlases </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> show_all_atlases </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> find_reasons </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> show_all_reasons </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> find_cached_files </td>
   <td style="text-align:left;font-weight: bold;color: #7f9959 !important;"> show_all_cached_files </td>
  </tr>
</tbody>
</table>


## `galah_` functions

Functions that alter or filter data requests use the prefix `galah_`. These functions include:

-   `galah_filter`
-   `galah_select`
-   `galah_group_by`
-   `galah_geolocate`

These functions replace or extend functions previously prefixed by `select_`. 
Renaming `select_` functions to `galah_` functions reflects `galah`'s embrace of
`dplyr`. This change can be seen in the names of `galah_` functions; they echo 
`dplyr`'s `filter`, `select` and `group_by` functions.

The similarity of `galah_` functions to `dplyr` doesn't end there. `galah_filter`, 
`galah_select` and `galah_group_by` also use `dplyr` tidy evaluation and syntax. 
This means that the way you use `dplyr` functions is also how you use `galah_` 
functions.

Let's look at a few examples to show you what we mean.

Use `galah_filter` to filter the rows of queries:


```r
# Get total record count since 2000
atlas_counts(filter = galah_filter(year > 2000))
```

```
## [1] 62703130
```

```r
# Get total record count for iNaturalist in 2021
atlas_counts(
  filter = galah_filter(year == 2021,
                        dataResourceName == "iNaturalist Australia"))
```

```
## [1] 889799
```

Use `galah_group_by` to group record counts and summarise counts by specified fields:


```r
# Get record counts since 2010, grouped by year and basis of record
galah_config(verbose = FALSE)
atlas_counts(
  filter = galah_filter(year > 2015 & year <= 2020),
  group_by = galah_group_by(year, basisOfRecord, expand = TRUE)
  )
```

```
##    year       basisOfRecord   count
## 1  2020   HUMAN_OBSERVATION 5813680
## 2  2020  PRESERVED_SPECIMEN   13587
## 3  2020         OBSERVATION    2863
## 4  2020             UNKNOWN     365
## 5  2020     MATERIAL_SAMPLE     250
## 6  2020     LIVING_SPECIMEN     127
## 7  2020 MACHINE_OBSERVATION      37
## 8  2019   HUMAN_OBSERVATION 5397407
## 9  2019             UNKNOWN   51747
## 10 2019  PRESERVED_SPECIMEN   38060
## 11 2019         OBSERVATION    6858
## 12 2019     MATERIAL_SAMPLE    5515
## 13 2019     LIVING_SPECIMEN    1460
## 14 2019 MACHINE_OBSERVATION     652
## 15 2018   HUMAN_OBSERVATION 5266669
## 16 2018             UNKNOWN   80208
## 17 2018  PRESERVED_SPECIMEN   44186
## 18 2018         OBSERVATION   17057
## 19 2018     MATERIAL_SAMPLE    3945
## 20 2018 MACHINE_OBSERVATION     579
## 21 2018     LIVING_SPECIMEN      69
## 22 2017   HUMAN_OBSERVATION 4342497
## 23 2017     MATERIAL_SAMPLE  167368
## 24 2017  PRESERVED_SPECIMEN   72426
## 25 2017             UNKNOWN   30950
## 26 2017         OBSERVATION   26229
## 27 2017     LIVING_SPECIMEN     428
## 28 2017 MACHINE_OBSERVATION     279
## 29 2016   HUMAN_OBSERVATION 3568570
## 30 2016     MATERIAL_SAMPLE  129231
## 31 2016  PRESERVED_SPECIMEN   76877
## 32 2016         OBSERVATION   31327
## 33 2016 MACHINE_OBSERVATION   18370
## 34 2016             UNKNOWN   16516
## 35 2016     LIVING_SPECIMEN     653
```

Use `galah_select` to choose columns returned when downloading records:


```r
# Get records from 1930, but only 'eventDate' and 'kingdom' columns
atlas_occurrences(
  filter = galah_filter(year == 1930),
  select = galah_select(eventDate, kingdom)
  ) |>
  head() # only return first 5 lines
```

Use `galah_geolocate` to specify a geographic area or region to limit your search:


```r
# Get list of parameles species only in area specified:
# (Note: This can also be specified by a shapefile)
wkt <- "POLYGON((131.36328125 -22.506468769126,135.23046875 -23.396716654542,134.17578125 -27.287832521411,127.40820312499 -26.661206402316,128.111328125 -21.037340349154,131.36328125 -22.506468769126))"

species <- atlas_species(geolocate = galah_geolocate(wkt))
```

`galah_` functions also evaluate arguments just like `dplyr`. To see what we mean, 
let's look at an example of how `dplyr::filter()` works. Notice how `dplyr::filter` 
and `galah_filter` both require logical arguments to be added by using the `==` sign:


```r
library(dplyr)

mtcars %>% filter(mpg == 21)
```

```
##               mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
## Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```


```r
atlas_counts(filter = galah_filter(year == 2021))
```

```
## [1] 1073650
```

As another example, notice how `galah_group_by` works very similarly to
 `dplyr::group_by` + `dplyr::summarise(sum())`:


```r
mtcars %>% 
  group_by(vs) %>% 
  summarise(sum(mpg))
```

```
## # A tibble: 2 × 2
##      vs `sum(mpg)`
##   <dbl>      <dbl>
## 1     0       299.
## 2     1       344.
```

```r
atlas_counts(group_by = galah_group_by(biome))
```

```
##         biome    count
## 1 TERRESTRIAL 93280944
## 2      MARINE  3504573
```


We made this move towards tidy evaluation to eventually make it possible to use
 piping to create a query to the Atlas of Living Australia just like how you might 
 edit a `data.frame` with the `tidyverse`. We are not ready to add these changes, 
 but we imagine that getting the number of records, for example, could look 
 something like this in the future:


```r
galah_call() %>%
  search_taxa("parameles") %>%
  galah_filter(year == 2021) %>%
  galah_group_by(species, year) %>%
  atlas_counts()
```


## `search_taxa`

`search_taxa` replaces the previously named `select_taxa`. This change in syntax 
reflects the function's primary use - to search for taxonomic information. For 
example, to search for reptiles, we first need to identify whether we have the 
correct query and verify using additional taxonomic information:


```r
search_taxa("Reptilia")
```

```
##   search_term scientific_name                                                            taxon_concept_id  rank match_type  kingdom
## 1    Reptilia        REPTILIA urn:lsid:biodiversity.org.au:afd.taxon:682e1228-5b3c-45ff-833b-550efd40c399 class exactMatch Animalia
##     phylum    class  issues
## 1 Chordata Reptilia noIssue
```

The output confirms that *Reptilia* is the correct search term, which we can use 
in `atlas_` functions to narrow our results or records. This output is consistent 
with the other `search_` function, `search_fields`.


## `atlas_` functions

The prefix `atlas_` replaces `ala_` for the functions

-   `atlas_counts`
-   `atlas_occurrences`
-   `atlas_species`
-   `atlas_media`
-   `atlas_taxonomy`
-   `atlas_citation`

This change was made to reflect the ability for functions like `atlas_counts` and 
`atlas_occurrences` to use international atlases since galah 1.2.0 
(see `vignette("international_atlases")`).

`atlas_` functions work the same as previous `ala_` functions, but with changes 
to the names of arguments they accept. Argument names are consistent with the 
functions that they use. With the new syntax of `galah_` functions and the
 update to `search_taxa`, these argument changes look like this:


```r
# Get species list for Perameles (aka Bandicoots)
atlas_species(taxa = search_taxa("perameles"))

# Get record counts of Perameles by year since 2010
atlas_counts(taxa = search_taxa("perameles"),
             filter = galah_filter(year > 2010),
             group_by = galah_group_by (year))

# Get records of Perameles from 2010, with "basis of record" included as a column
atlas_occurrences(taxa = search_taxa("perameles"),
                  filter = galah_filter(year == 2010),
                  select = galah_select(basisOfRecord, group = "basic"),
                  geolocate = wkt) # wkt was defined in earlier example

# Get taxonomic tree of Peramelemorphia (aka bandicoots & bilbies) down to genus
atlas_taxonomy(taxa = search_taxa("Peramelemorphia"),
               down_to = "genus")

# Download media of Regent Honeyeater from 2010
atlas_media(taxa = search_taxa("Regent Honeyeater"),
            filter = galah_filter(year == 2010),
            download_dir = "media")
```

See R help files for more information on using `atlas_` functions with updated syntax.


## `show_all_` functions

Functions with the prefix `show_all_` return a `data.frame` doing exactly that 
- showing all the possible values of the category specified. These functions include:

-   `show_all_fields`
-   `show_all_atlases`
-   `show_all_ranks`
-   `show_all_profiles`
-   `show_all_reasons`
-   `show_all_cached_files`

`show_all_` functions require no arguments. Simply call the function and it will 
return all accepted values:


```r
show_all_atlases()
```

```
##       atlas taxonomy_source                                                     taxonomy_info
## 1 Australia             ALA                                           https://bie.ala.org.au/
## 2   Austria            GBIF https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
## 3 Guatemala            GBIF https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
## 4     Spain            GBIF https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
## 5    Sweden            GBIF https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
## 6        UK             NBN            https://www.nhm.ac.uk/our-science/data/uk-species.html
```

```r
show_all_reasons()
```

```
##    id                             name
## 0   0 conservation management/planning
## 1   1  biosecurity management/planning
## 2   2         environmental assessment
## 3   3                        education
## 4   4              scientific research
## 5   5            collection management
## 6   6                            other
## 7   7              ecological research
## 8   8     systematic research/taxonomy
## 10 10                          testing
## 11 11                  citizen science
## 12 12          restoration/remediation
## 13 13                species modelling
```


## Deprecated syntax

Old syntax will now return an error when used, suggesting the new syntax. 

New syntax are not fully decided on and can be changed in future versions of 
`galah`. We would appreciate any feedback from users about what works or what 
doesn't work. It is our goal to create a package that is as easy and intuitive 
for users as possible!

