---
title: "Syntax changes"
author: "Martin Westgate & Dax Kellie"
date: '2022-01-24'
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Syntax changes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Version 1.4.0 brings in three major changes in how `galah` works:
  
- use of non-standard evaluation (NSE) in functions that modify queries
- updated function naming
- support for piping via `galah_call`
  
Below we discuss each of these changes in turn. Please note, however, that these 
changes are by no means set in stone - it is absolutely possible to 
change syntax in future versions of `galah` if alternative names are easier to 
use and understand. We would appreciate any feedback from users about what works 
or what doesn't work. It is our goal to create a package that is as easy and 
intuitive for users as possible!


# NSE and comparison to `dplyr`
`galah_` functions now evaluate arguments just like `dplyr`. To see what we mean, 
let's look at an example of how `dplyr::filter()` works. Notice how `dplyr::filter` 
and `galah_filter` both require logical arguments to be added by using the `==` sign:


```r
library(dplyr)

mtcars %>% 
  filter(mpg == 21)
```

```
##               mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
## Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

```r
galah_call() %>% 
  galah_filter(year == 2021) %>% 
  atlas_counts()
```

```
## # A tibble: 1 × 1
##     count
##     <int>
## 1 1161557
```

As another example, notice how `galah_group_by()` + `atlas_counts()` works very 
similarly to `dplyr::group_by()` + `dplyr::count()`:


```r
mtcars %>% 
  group_by(vs) %>% 
  count()
```

```
## # A tibble: 2 × 2
## # Groups:   vs [2]
##      vs     n
##   <dbl> <int>
## 1     0    18
## 2     1    14
```

```r
galah_call() %>%
  galah_group_by(biome) %>%
  atlas_counts()
```

```
## # A tibble: 2 × 2
##   biome          count
##   <chr>          <int>
## 1 TERRESTRIAL 93590939
## 2 MARINE       3519480
```

We made this move towards tidy evaluation to make it possible to use 
piping for building queries to the Atlas of Living Australia. In practice, this 
means that data queries can be filtered just like how you might 
filter a `data.frame` with the `tidyverse` suite of functions. 


# Function naming
Prior to version 1.4.0, `galah` naming conventions had two major problems:

- download functions used the prefix `ala`, but actually could query many other living atlases
- query modifying functions used the prefix `select`, but this is reserved in `dplyr` (and elsewhere) for operations specifically on columns

To address these concerns (and other smaller points), we have completed a 
rewrite of our function names to increase clarity (see table below).
Deprecated function names will now return a warning message when used, suggesting
to users that they switch to the new syntax. 

<table class="table lightable-paper" style='width: auto !important; margin-left: auto; margin-right: auto; font-family: "Arial Narrow", arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;'>
 <thead>
  <tr>
   <th style="text-align:left;"> galah 1.3.1 and earlier </th>
   <th style="text-align:left;"> galah 1.4.0 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;color: #f064a4 !important;">  </td>
   <td style="text-align:left;font-weight: bold;color: #f064a4 !important;"> galah_call </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;"> select_taxa </td>
   <td style="text-align:left;color: #E06E53 !important;"> galah_identify </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;"> select_filters </td>
   <td style="text-align:left;color: #E06E53 !important;"> galah_filter </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;"> select_columns </td>
   <td style="text-align:left;color: #E06E53 !important;"> galah_select </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;"> select_locations </td>
   <td style="text-align:left;color: #E06E53 !important;"> galah_geolocate </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;">  </td>
   <td style="text-align:left;color: #E06E53 !important;"> galah_group_by </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;">  </td>
   <td style="text-align:left;color: #E06E53 !important;"> galah_down_to </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #E06E53 !important;color: #c7902a !important;"> ala_counts </td>
   <td style="text-align:left;color: #E06E53 !important;color: #c7902a !important;"> atlas_counts </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #c7902a !important;"> ala_occurrences </td>
   <td style="text-align:left;color: #c7902a !important;"> atlas_occurrences </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #c7902a !important;"> ala_species </td>
   <td style="text-align:left;color: #c7902a !important;"> atlas_species </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #c7902a !important;"> ala_media </td>
   <td style="text-align:left;color: #c7902a !important;"> atlas_media </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #c7902a !important;"> ala_taxonomy </td>
   <td style="text-align:left;color: #c7902a !important;"> atlas_taxonomy </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #c7902a !important;"> ala_citation </td>
   <td style="text-align:left;color: #c7902a !important;"> atlas_citation </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> select_taxa </td>
   <td style="text-align:left;color: #7f9959 !important;"> search_taxa, search_identifiers </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> search_fields </td>
   <td style="text-align:left;color: #7f9959 !important;"> search_fields </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;">  </td>
   <td style="text-align:left;color: #7f9959 !important;"> show_all_fields </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_profiles </td>
   <td style="text-align:left;color: #7f9959 !important;"> show_all_profiles </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_ranks </td>
   <td style="text-align:left;color: #7f9959 !important;"> show_all_ranks </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_atlases </td>
   <td style="text-align:left;color: #7f9959 !important;"> show_all_atlases </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_reasons </td>
   <td style="text-align:left;color: #7f9959 !important;"> show_all_reasons </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_cached_files </td>
   <td style="text-align:left;color: #7f9959 !important;"> show_all_cached_files </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_field_values </td>
   <td style="text-align:left;color: #7f9959 !important;"> search_field_values </td>
  </tr>
  <tr>
   <td style="text-align:left;color: #7f9959 !important;"> find_profile_attributes </td>
   <td style="text-align:left;color: #7f9959 !important;"> search_profile_attributes </td>
  </tr>
</tbody>
</table>

# Piping with `galah_call()`

Perhaps the largest change from `galah` 1.4.0 is the implementation of piping 
using `galah_call()`. 

Beginning a query with `galah_call()` (be sure to add the parentheses!) tells 
`galah` that you will be using pipes to construct your query. Follow this with 
your preferred pipe (`|>` from `base` or `%>%` from `magrittr`). You can then 
narrow your query line-by-line using `galah_` functions. Finally, end with an 
`atlas_` function to identify what type of data you want from your query.  
  
Unlike old function names, which will be removed from future versions, we do intend to 
continue supported un-piped syntax in future, although piping only works with 
revamped function names. If you're new to piping, here's a comparison against
code from previous versions of `galah`.

Previously, if you wanted to look up the number of records of each bandicoot 
species every year from 2010 to 2021, you'd have had to do 
something like this:
  

```r
library(purrr)
library(dplyr)

taxa <- ala_species(taxa = select_taxa("perameles"))$species
years <- select_filters(year = seq(2010:2021))

taxa %>%
  map_dfr( ~ ala_counts(
    taxa = select_taxa(list(species = .x)),
    filters = years,
    group_by = "year")
```
  
Not very easy because you had to use multiple `atlas_` functions and you had to 
use loops. However, now with piping you can do it like this:


```r
galah_call() %>%
  galah_identify("perameles") %>%
  galah_filter(year > 2010) %>%
  galah_group_by(species, year) %>%
  atlas_counts()
```

And a second example, if you wanted to download occurrence records of bandicoots 
in 2021, and also to include information on which records had zero coordinates, 
previously you would have had to do this:
  



```r
atlas_occurrences(taxa = select_taxa("perameles"),
                  filters = select_filters(year = 2021),
                  columns = select_columns(group = "basic", "ZERO_COORDINATE"))
```

Now with piping:


```r
galah_call() %>%
  galah_identify("perameles") %>%
  galah_filter(year == 2021) %>%
  galah_select(group = "basic", ZERO_COORDINATE) %>%
  atlas_occurrences()
```
