---
title: "Taxonomic searches"
author: "Martin Westgate & Matilda Stevenson"
date: '2022-01-12'
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Taxonomic searches}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



`galah` provides multiple ways of retrieving taxonomic information, and the best
method depends of the type of information required. Below, some use cases are
outlined. 

## Searching for a single species or clade

The simplest way to get taxonomic information is to use `search_taxa`. This function
takes one or more scientific names and checks them against the ALA's taxonomy 
service.

```r
library(galah)
search_taxa("Chordata")
```

```
## # A tibble: 1 × 9
##   search_term scientific_name taxon_concept_id                   rank   match_type kingdom phylum vernacular_name issues
##   <chr>       <chr>           <chr>                              <chr>  <chr>      <chr>   <chr>  <chr>           <chr> 
## 1 Chordata    CHORDATA        urn:lsid:biodiversity.org.au:afd.… phylum exactMatch Animal… Chord… vertebrates     noIss…
```

By default, this function shows the search term, the match (if any) within the ALA,
and some information on higher taxonomy of that clade. Critically, it also
returns a unique identifier for that clade, stored in the column 
`taxon_concept_id`. This identifer is the information that the ALA needs to 
return data that is specific to the taxon in question, i.e.:

```r
atlas_counts(taxa = search_taxa("Chordata"))
```

```
## # A tibble: 1 × 1
##      count
##      <int>
## 1 69191085
```

`search_taxa` can accept a vector or a `data.frame` of taxonomic names,
and always returns a `data.frame` with the same number of rows as there are 
names to query. 

One final, useful feature of `search_taxa` is that it works in reverse. That is,
if you have a unique identifier and would like to know which taxon it refers to,
you can find that out by setting `is_id` to `TRUE`:


```r
search_taxa("urn:lsid:biodiversity.org.au:afd.taxon:97764bed-9492-4066-a45f-e5b0c6c4280d", is_id = TRUE)
```

## Taxonomic filtering
`search_taxa()` enables users to search for taxonomic names, check that the results
are 'correct', and use their results to download data.
The function allows both free-text searches and searches that specify by rank(s). 
Specifying additional ranks in a `data.frame` or `tibble` can be useful when 
names are ambiguous.

```r
# Free-text search
taxa <- search_taxa("Eolophus")

# Search specifying ranks
search_taxa(query = data.frame(genus = "Eolophus", kingdom = "Aves"))
```

```
## Error in validate_signal_message(message, class): object 'mesg' not found
```

For more detailed taxonomic information, you can also use `atlas_taxonomy()`, 
as outlined in `vignette("taxonomic_information")`



## Advanced taxonomic queries
Although we have focussed above on functions that are built to integrate
taxonomic concepts, the more general `galah_filter` can be used to 
build more flexible queries using the `taxonConceptID` field.
This can be useful for paraphyletic concepts such as invertebrates:


```r
invertebrate_filter <- galah_filter(
   taxonConceptID == search_taxa("Animalia")$taxon_concept_id,
   taxonConceptID != search_taxa("Chordata")$taxon_concept_id)
head(atlas_counts(galah_filter = invertebrate_filter, 
                  group_by = galah_group_by(class)))
```

```
## Error in atlas_counts.default(galah_filter = invertebrate_filter, group_by = galah_group_by(class)): unused argument (galah_filter = invertebrate_filter)
```

## Using taxonomic filters for another atlas
`galah` only supports searching for Australian taxonomy; for other Atlases,
`taxize` should be used to search for the taxonomic id, and this id can be passed
to the `taxa` argument of `atlas_` functions. For example:

```r
library(taxize)
# Use UK taxonomy
id <- get_nbnid("Vulpes vulpes", rows = 1)
```

```
## ══  1 queries  ═══════════════
```

```
## 
## Retrieving data for taxon 'Vulpes vulpes'
```

```
## ✔  Found:  Vulpes vulpes
## ══  Results  ═════════════════
## 
## • Total: 1 
## • Found: 1 
## • Not Found: 0
```

```r
atlas_counts(taxa = id)
```

```
## Error in if (nrow(taxa) < 1) {: argument is of length zero
```
