# Warning generated by `galah_identify()` about empty query
test_that("galah_identify returns an empty tibble when no args provided", {
  expect_warning({result <- galah_identify()})
  expect_equal(nrow(result), 0)
  expect_warning(galah_identify(), "No query passed")
})

test_that("galah_identify runs a search when given a string", {
  result <- galah_identify("Litoria peronii")
  expect_equal(nrow(result), 1)
})

test_that("galah_identify runs a search on multiple strings", {
  result <- galah_identify("amphibia", "reptilia", "aves", "mammalia")
  expect_equal(nrow(result), 4)
})

test_that("galah_identify runs a search on multiple strings wrapped by c()", {
  search_terms <- c("amphibia", "reptilia", "aves", "mammalia")
  result <- galah_identify(search_terms)
  expect_equal(nrow(result), 4)
})

## obsolete: use `filter(lsid == )` instead
# test_that("galah_identify works with search = FALSE", {
#   galah_config(run_checks = FALSE)
#   id <- "urn:lsid:biodiversity.org.au:afd.taxon:0490a9ba-0d08-473d-a709-6c42e354f118"
#   result <- galah_identify(id, search = FALSE)
#   expect_equal(result$identifier[1], id)
# })
# 
# test_that("galah_identify can pass a string unchanged when run_checks = FALSE", {
#   galah_config(run_checks = FALSE)
#   result <- galah_identify("a_string", search = FALSE)
#   expect_equal(nrow(result), 1)
#   expect_equal(result$identifier[1], "a_string")
# })

test_that("galah_identify pipes correctly", {
  result <- galah_call() |>
    galah_identify("Litoria") |>
    galah_filter(year == 2020)
  expect_false(is.null(result$identify))
  expect_false(is.null(result$filter))
})

test_that("galah_identify pipes correctly when taxa are partially returned", {
  galah_config(verbose = FALSE)
  result <- galah_call() |>
    galah_identify("Litoria", "blarghy") |>
    galah_filter(year == 2020)
  expect_false(is.null(result$identify))
  expect_false(is.null(result$filter))
  galah_config(verbose = TRUE)
})


test_that("galah_identify warns when taxa are partially returned", {
  expect_warning(
    galah_call() |>
      galah_identify("Litoria", "blarghy") |>
      galah_filter(year == 2020),
    "Unmatched taxa"
  )
  expect_warning(
    galah_identify("Litoria", "blarghy"),
    "Unmatched taxa"
  )
})

test_that("galah_identify warns when identifiers are partially returned", {
  galah_config(run_checks = TRUE)
  ids <- c("https://biodiversity.org.au/afd/taxa/0df99ece-1982-4605-a2b3-4fcb7660ee2b",
           "https://id.biodiversity.org.au/node/apni/2910467",
           "https://id.biodiversity.org.au/node/apni/291047") # wrong id
  expect_warning(
    galah_call() |>
      galah_identify(ids, search = FALSE) |>
      galah_filter(year == 2020),
    "Unmatched taxa"
  )
  expect_warning(
    galah_identify(ids, search = FALSE),
    "Unmatched taxa"
  )
})