#'Build a query
#'
#'@export

ala_query <- function(taxa = NULL, filters = NULL, locations = NULL){
  
  if(!is.null(taxa)) {
    check_taxa_arg(taxa)
    }
  
  if(!is.null(filters) && !any(grepl("ala_filters", class(filters)))){
    stop("`filters` argument requires an identifier input generated by `select_filters()`")
  }
  
  if(!is.null(locations) && !any(grepl("ala_locations", class(locations)))){
    stop("`locations` argument requires an identifier input generated by `select_locations()`")
  }
  
  query <- structure(list(taxa = taxa, 
                          filters = filters,
                          locations = locations), class = "ala_query")
  
  return(query)
}



# new_ala_query <- function(x = list){
#   stopifnot(is.list(x))
#   structure(x, class = "")
# }