#' Species list
#'
#' @param taxa data.frame: generated by a call to \code{\link{select_taxa}}. This
#' argument also accepts a vector of unique species identifiers.
#' @param filters data.frame: generated by a call to \code{\link{select_filters}}
#' @param locations string: generated by a call to \code{\link{select_locations}}
#' @return \code{data.frame} of matching species, with optional additional details.
#' @export ala_species

# If the facet search download worked properly, this should also return counts. But, as this
# function is likely to be used to download long species lists, for now we will make do
# without the counts- otherwise will require lots of pagination.
ala_species <- function(taxa, filters, locations) {
  # Use facet search with additional options

  url <- getOption("galah_server_config")$base_url_biocache

  query <- list()
  
  if (missing(taxa) & missing(filters) & missing(locations)) {
    warning("This query will return a list of all species in the ALA")
  }

  if (!missing(taxa)) {
    # should species id be validated?
    if (inherits(taxa, "data.frame") &&
        "taxon_concept_id" %in% colnames(taxa)) {
      taxa <- taxa$taxon_concept_id
    }
    assert_that(is.character(taxa))
    taxa_query <- build_taxa_query(taxa)
  } else {
    taxa_query <- NULL
  }

  # validate filters
  if (!missing(filters)) {
    assert_that(is.data.frame(filters))
    filter_query <- build_filter_query(filters)
  } else {
    filter_query <- NULL
  }

  query$fq <- c(taxa_query, filter_query)

  if (!missing(locations)) {
    area_query <- locations
    query$wkt <- locations
  } else {
    area_query <- NULL
  }

  if (check_for_caching(taxa_query, filter_query, area_query)) {
    query <- cached_query(taxa_query, filter_query, area_query)
  }

  query$facets <- "species_guid"
  query$lookup  <- "true"
  #query$counts <- "true"

  path <- "ws/occurrences/facets/download"

  cache_file <- cache_filename(c(url, path, unlist(query)), ext = ".csv")

  caching <- getOption("galah_config")$caching
  
  if (caching && file.exists(cache_file)) {
    message("Using cached file")
    return(read.csv(cache_file))
  }

  data <- ala_download(url, path = path, params = query,
                       cache_file = cache_file)
  # overwrite file with fixed names
  names(data) <- rename_columns(names(data), type = "checklist")
  
  if (caching) {
    write.csv(data, cache_file)
  }
  return(data)
}