#' Internal function to convert `data_request` with `type = "doi"` to a `query`
#' @noRd
#' @keywords Internal
as_query_occurrences_doi <- function(.query, 
                                     error_call = caller_env()){
  if(is.null(.query$filter)){
    cli::cli_abort("A DOI must be specified using `filter(doi == \"my-doi-here\")`.", 
                   call = error_call)
  }
  
  if(is.null(.query$filter$variable) && .query$filter$variable != "doi"){
    cli::cli_abort("No DOI has been supplied.", 
                   call = error_call)
  }
  
  atlas <- potions::pour("atlas", "acronym")
  if(!(atlas %in% c("ALA", "GBIF"))){
    c(
      "DOI downloads not supported by selected atlas.",
      i = "`request_data(type = \"occurrences-doi\")` has only been implemented for ALA & GBIF") |>
    cli::cli_abort(call = error_call)    
  }
  
  doi <- .query$filter$value[[1]]
  
  # remove "https://" if present
  if (grepl("^http://doi.org/", doi)) {
    doi <- sub("^https://doi.org/", "", doi)
  }
  
  # extract useful part of DOI
  doi_str <- stringr::str_split(doi, "ala.")[[1]][2]
  if(is.na(doi_str)){
    c(
      "DOI has not been generated by the ALA.",
      i = "DOIs created by the ALA have a prefix of 10.26197/ala.") |>
    cli::cli_abort(call = error_call)
  }
  
  result <- list(
    type = "data/occurrences-doi",
    url = url_lookup("data/occurrences-doi", 
                     doi_string = doi_str),
    headers = build_headers(),
    download = TRUE)
  class(result) <- "data_query"
  return(result)
}
