#' Generate a citation for occurrence data
#'
#' If a `data.frame` was generated using [atlas_occurrences()],
#' and the `mint_doi` argument was set to `TRUE`, the DOI associated
#' with that dataset is appended to the resulting `data.frame` as an
#' attribute. This function simply formats that DOI as a citation that can be 
#' included in a scientific publication. Please also consider citing this 
#' package, using the information in `citation("galah")`.
#' @param data data.frame: occurrence data generated by 
#' [atlas_occurrences()]
#' @return A string containing the citation for that dataset.
#' @examples \dontrun{
#' atlas_citation(doi)
#' }
#' @export

atlas_citation <- function(data) {
  # get basic information from file
  modified_date <- attributes(data)$modified_date
  doi <- attributes(data)$doi
  citation <- attributes(data)$citation
  search_url <- attributes(data)$search_url
  
  # get existing citation info
  r_citation <- citation() |>
    print(style = 'text') |> 
    utils::capture.output() |>
    glue_collapse(sep = " ")
  galah_citation <- citation(package = "galah") |>
    print(style = 'text') |> 
    utils::capture.output() |>
    glue_collapse(sep = " ")
  
  # set case when DOI is missing
  if (is.null(doi)) {
    if(!is.null(citation)){
      glue("
      The citation for this dataset is:
      
           {citation}
         
       ") |>
        cat()
    }else{
      bullets <- c(
        "This dataset does not have any citation information attached.",
        i = "Please consider checking the atlas in question for their citation guidelines"
      )
      warn(bullets, call = caller_env())      
    }
  }else{ # i.e. if DOI present
    if(grepl("10.26197/ala.", doi)){
      org_text <- "Atlas of Living Australia"
      description <- "Occurrence download"
    }else{
      org_text <- "GBIF.org"
      description <- "GBIF Occurrence Download"
    }
    
    glue("
      The citation for this dataset is:
      
         {org_text} ({modified_date}) {description} {doi}
         
       ") |> cat()
  }
  glue("
  
  Please consider citing R & galah, in addition to your dataset:
       
         {r_citation}
         
         {galah_citation}")
}
