#' Get metadata on images, sounds and videos
#'
#' In addition to text data describing individual occurrences and their 
#' attributes, ALA stores images, sounds and videos associated with a given 
#' record. `atlas_media` displays metadata for any and all of the media types. 
#'
#' @param request optional `data_request` object: generated by a call to
#' [galah_call()].
#' @param identify `data.frame`: generated by a call to
#' [galah_identify()].
#' @param filter `data.frame`: generated by a call to
#' [galah_filter()]
#' @param geolocate `string`: generated by a call to
#' [galah_geolocate()]
#' @param data_profile `string`: generated by a call to
#' [galah_apply_profile()]
#' @details [atlas_media()] works by first finding all occurrence records
#' matching the filter which contain media, then downloading the metadata for the
#' media. To actually download the files themselves, use [collect("media")].
#' It may be beneficial when requesting a large number of records to show a progress
#' bar by setting `verbose = TRUE` in [galah_config()].
#' @return An object of class `tbl_df` and `data.frame` (aka a tibble) 
#' of metadata of the requested media.
#' @seealso [atlas_counts()] to find the number of records with media; but note this
#' is not necessarily the same as the number of media files, as each record can have
#' more than one media file associated with it (see examples section for how to do this).
#' 
#' @examples \dontrun{
#' # Download Regent Honeyeater records with multimedia attached
#' galah_call() |>
#'   galah_identify("Regent Honeyeater") |>
#'   galah_filter(year == 2011) |>
#'   atlas_media()
#' 
#' # Download multimedia
#' galah_call() |>
#'   galah_identify("Regent Honeyeater") |>
#'   galah_filter(year == 2011) |>
#'   atlas_media() |>
#'   collect_media(path = "folder/your-directory")
#' 
#' # Specify a single media type to download
#' galah_call() |>
#'   galah_identify("Eolophus Roseicapilla") |>
#'   galah_filter(multimedia == "Sound") |>
#'   atlas_media()
#' 
#' # It's good to check how many records have media files before downloading
#' galah_call() |>
#'   galah_filter(multimedia == c("Image", "Sound", "Video")) |>
#'   galah_group_by(multimedia) |>
#'   atlas_counts()
#'}
#' @importFrom dplyr bind_rows
#' @importFrom dplyr filter
#' @importFrom dplyr relocate
#' @importFrom dplyr right_join
#' @importFrom dplyr select
#' @importFrom glue glue
#' @importFrom potions pour
#' @importFrom tibble tibble
#' @importFrom tidyr unnest_longer
#' @export
atlas_media <- function(request = NULL, 
                        identify = NULL, 
                        filter = NULL, 
                        select = NULL,
                        geolocate = NULL,
                        data_profile = NULL
                        ) {
  
  if(pour("atlas", "region") != "Australia"){
    abort("`atlas_media` is currently only supported for the Atlas of Living Australia")
  }
  
  # capture supplied arguments
  args <- as.list(environment())
  
  # convert to `data_request` object
  .data <- check_atlas_inputs(args)
  .data$type <- "occurrences" # default, but in case supplied otherwise
  
  
  # ensure media columns are present in `select`
  valid_formats <- c("images", "videos", "sounds")
  if(is.null(.data$select)){
    .data <- update_data_request(.data, 
                                 select = galah_select(group = c("basic", "media")))
  }else{
    if(!any(.data$select$name %in% valid_formats)){
      .data <- update_data_request(.data, 
                                   select = galah_select(group = "media"))
    }
  }
  
  # filter to records that contain media of requested types 
  # NOTE: Might be more efficient to use `filter` for this, as it 
  # includes code to remove duplicated rows
  if(is.null(.data$filter)){
    abort("You must specify a valid `filter()` to use `atlas_media()`")
  }
  present_formats <- valid_formats[valid_formats %in% .data$select$name]
  media_fq <- glue("({present_formats}:*)") |>
    glue_collapse(" OR ")
  media_fq <- glue("({media_fq})")
  .data$filter <- bind_rows(.data$filter, 
                            tibble(variable = "media",
                                   logical = "==",
                                   value = paste(valid_formats, collapse = "|"),
                                   query = as.character(media_fq)))
  
  # get occurrences
  occ <- .data |> 
    collect(wait = TRUE) # Q: what if this errors?
  # format
  occ <- occ |> 
    unnest_longer(col = present_formats)
  occ$media_id <- build_media_id(occ) # this integrates all types of identifier
  occ <- occ |>
    filter(!is.na(media_id)) |>
    select(-multimedia, -images, -videos, -sounds)
  
  # collect media in a loop
  media <- request_data(type = "media") |>
    filter(media_id == occ$media_id) |>
    collect()
  
  # join and return
  right_join(occ, media, by = "media_id") |>
    relocate(media_id, 1)
}

#' Internal function to get media metadata, and create a valid file name
#' @noRd
#' @keywords Internal
build_media_id <- function(df){
  # create a column that includes media identifiers, regardless of which column they are in
  ## NOTE: I haven't found good tidyverse syntax for this yet
  x <- rep(NA, nrow(df))
  videos <- !is.na(df$videos)
  if(any(videos)){x[videos] <- df$videos[videos]}
  sounds <- !is.na(df$sounds)
  if(any(sounds)){x[sounds] <- df$sounds[sounds]}
  images <- !is.na(df$images)
  if(any(images)){x[images] <- df$images[images]}
  x
}