#' Internal function to convert `data_request` with `type = "occurrences"` to a `query`
#' @noRd
#' @keywords Internal
capture_occurrences <- function(.query,
                                 ...,
                                 call = rlang::caller_env()){
  if(is.null(.query$filter) & 
     is.null(.query$identify) & 
     is.null(.query$geolocate)){
    cli::cli_abort("No filters supplied to `capture()` with `type = \"occurrences\"`",
                   call = call)
  }
  switch(.query$atlas,
         "Global" = capture_occurrences_gbif(.query, ...),
         capture_occurrences_la(.query, ...))
}

#' calculate the query to be returned for GBIF
#' @noRd
#' @keywords Internal
capture_occurrences_gbif <- function(.query, 
                                      format = "SIMPLE_CSV",
                                      ...){
  # get user string
  .query$type <- "data/occurrences"
  username <- .query$authenticate$username
  password <- .query$authenticate$password
  user_string <- glue::glue("{username}:{password}")
  
  # build object
  list(type = .query$type,
       atlas = .query$atlas,
       url = url_lookup(.query),
       headers =  list(
         `User-Agent` = galah_version_string(), 
         `X-USER-AGENT` = galah_version_string(),
         `Content-Type` = "application/json",
         Accept = "application/json"),
       options = list(
         httpauth = 1,
         userpwd = user_string),
       body = list(filter = .query$filter, 
                   identify = .query$identify,
                   geolocate = .query$geolocate,
                   format = "SIMPLE_CSV")) |>
    as_prequery()
}

#' calculate the query to be returned for a given living atlas
#' @param .query An object of class `data_request()`
#' @noRd
#' @keywords Internal
capture_occurrences_la <- function(.query,
                                   mint_doi = FALSE){
  .query$type <- "data/occurrences"
  # build a query
  query <- c(build_query(identify = .query$identify,
                         filter = .query$filter, 
                         geolocate = .query$geolocate, 
                         apply_profile = .query$apply_profile,
                         atlas = .query$atlas),
             fields = "`SELECT_PLACEHOLDER`",
             qa = "`ASSERTIONS_PLACEHOLDER`",
             facet = "false",
             sourceTypeId = source_type_id_lookup(.query$atlas),
             reasonTypeId = .query$authenticate$download_reason_id,
             dwcHeaders = "true") |>
    add_email_notify() |>
    add_email_address(query = .query) |>
    add_doi_request(mint_doi = mint_doi,
                    atlas = .query$atlas)

  # build url
  url <- url_lookup(.query) |>
    httr2::url_parse()
  url$query <- query
  
  # build output
  list(type = .query$type,
       atlas = .query$atlas,
       url = httr2::url_build(url),
       headers = build_headers()) |>
    as_prequery()
}

#' Internal function to convert `data_request` with `type = "doi"` to a `query`
#' @noRd
#' @keywords Internal
capture_occurrences_doi <- function(.query, 
                                    error_call = rlang::caller_env()){
  .query$type <- "data/occurrences-doi"

  # check for a doi filter
  if(is.null(.query$filter)){
    cli::cli_abort("A DOI must be specified using `filter(doi == \"my-doi-here\")`.", 
                   call = error_call)
  }
  
  # check that doi is supplied 'correctly'
  if(inherits(.query$filter, "predicates_filter")){
    doi_missing_check <- .query$filter$key != "DOI"
  }else{
    doi_missing_check <- is.null(.query$filter$variable) && .query$filter$variable != "doi"
  }
  
  # check atlas is ok
  if(!(.query$atlas %in% c("Australia", "Global"))){
    c(
      "DOI downloads not supported by selected atlas.",
      i = "`request_data(type = \"occurrences-doi\")` has only been implemented for ALA & GBIF") |>
    cli::cli_abort(call = error_call)    
  }
  
  # get doi
  doi <- .query$filter$value[[1]]
  
  # remove "https://" if present
  if (stringr::str_detect(doi, "^(http|https)://doi.org/")) {
    doi <- stringr::str_remove(doi, "^(http|https)://doi.org/")
  }
  
  # extract useful part of DOI
  
  if(.query$atlas == "Australia"){
    doi <- stringr::str_split(doi, "ala.")[[1]][2]
    if(is.na(doi)){
      c("DOI has not been generated by the ALA.",
        i = "DOIs created by the ALA have a prefix of 10.26197/ala.") |>
      cli::cli_abort(call = error_call)
    }
  }
  
  # build an object
  list(type = .query$type,
       atlas = .query$atlas,
       url = url_lookup(.query, 
                        doi_string = doi),
       headers = build_headers(),
       download = TRUE) |>
  as_query()
}

#' Internal function to convert `data_request` with `type = "occurrences-glimpse"` to a `query`
#' @noRd
#' @keywords Internal
capture_occurrences_glimpse <- function(.query){

  if(.query$atlas == "Global"){
    result <- capture_occurrences_count(.query)
    result$type <- "data/occurrences-glimpse"
    result$body$limit <- 3
    as_prequery(result)
  }else{
    .query$type <- "data/occurrences-glimpse"
    result <- capture_occurrences_la(.query)
    url <- httr2::url_parse(result$url)

    # replace path with count API
    url$path <- list(type = "data/occurrences-count",
                     atlas = .query$atlas) |>
      structure(class = c("data_request", "list")) |>
      url_lookup() |>
      httr2::url_parse() |>
      purrr::pluck("path") 
    url$query$pageSize <- 3 # add a pageSize arg
    result$url <- httr2::url_build(url) # rebuild
    result$type <- "data/occurrences-glimpse"

    # return
    as_prequery(result)
  }
}

#' Internal function to convert `data_request` with `type = "occurrences-decribe"` to a `query`
#' @noRd
#' @keywords Internal
capture_occurrences_describe <- function(.query){
  .query$type <- "data/occurrences-describe"
  x <- request_metadata(type = "fields", from = .query$atlas) |> 
    capture()
  update_request_object(x, type = .query$type)
}