#' Collect occurrence records from a pre-existing DOI
#'
#' This should be generated from `atlas_occurrences` or online
#'
#' @param doi `string`: this argument enables retrieval of occurrence
#' records previously downloaded from the ALA, using the DOI generated by the
#' data.
#'
#' @export

collect_doi <- function(doi){

  if(missing(doi)){
    stop <- TRUE
  }else{
    if(is.null(doi)){
      stop <- TRUE
    }else{
      stop <- FALSE
    }
  }
  if(stop){
    abort("Argument `doi` is missing, with no default")
  }
  
  result <- doi_download(doi)
  if(is.null(result)){
    bullets <- c(
      "Calling the API failed for `atlas_occurrences`.",
      i = "This might mean that the ALA system is down. Double check that your query is correct.",
      i = "If you continue to see this message, please email support@ala.org.au."
    )
    inform(bullets)
    return(tibble())
  }else{
    return(tibble(result))
  }
}


doi_download <- function(doi, error_call = caller_env()) {
  # strip useful part of DOI
  doi_str <- str_split(doi, "ala.")[[1]][2]
  if (is.na(doi_str)) {
    bullets <- c(
      "DOI has not been generated by the ALA.",
      i = "DOIs created by the ALA have a prefix of 10.26197/ala."
    )
    abort(bullets, call = error_call)
  }

  path <- ala_download(server_config("doi_base_url"),
                       path = paste0("/doi/", doi_str, "/download"),
                       ext = ".zip", cache_file = tempfile(pattern = "data"))
  if(is.null(path)){
    NULL
  }else{
    record_file <- grep("^records", unzip(path, list=TRUE)$Name, 
                        ignore.case=TRUE, value=TRUE)
    df <- read.csv(unz(path, record_file), stringsAsFactors = FALSE)
    attr(df, "doi") <- doi
    return(df)
  }
}