#' Collect occurrence records from a pre-existing DOI or URL
#'
#' @description `r lifecycle::badge("experimental")` 
#' 
#' Download occurrence records using an existing DOI or URL. Pre-existing DOIs 
#' and URLs come from previously generated downloads using `atlas_occurrences` 
#' or online.
#'
#'#' @param url `string`: Retrieve occurrence
#' records previously downloaded from the ALA, using the URL provided via email.
#' @param doi `string`: Retrieve occurrence
#' records previously downloaded from the ALA, using the DOI generated by the
#' data.
#'
#' @export collect_occurrences

collect_occurrences <- function(url, doi){

  if(missing(doi) & missing(url)){
    abort("one of either `doi` or `url` must be specified")
  }

  if(!missing(doi)){
    if(is.null(doi)){
      abort("Please specify a valid `doi`")
    }else if(grepl("^http", doi)){
      bullets <- c(
        "It looks like you have supplied a URL to the `doi` argument",
        i = "The `doi` argument does not accept DOIs formatted as URLs",
        i = "If you are supplying an ALA download url, pass it to `url` instead")
      abort(bullets)
    }else{
      result <- doi_download(doi)
    }
  }
  
  if(!missing(url)){
    if(is.null(url)){
      abort("Please specify a valid `url`")
    }else{
      result <- url_download(url)
    }
  } 
    
  if(is.null(result)){
    system_down_message("collect_occurrences")
    return(tibble())
  }else{
    return(tibble(result))
  }
  
}


doi_download <- function(doi, error_call = caller_env()) {
  # strip useful part of DOI
  doi_str <- str_split(doi, "ala.")[[1]][2]
  if (is.na(doi_str)) {
    bullets <- c(
      "DOI has not been generated by the ALA.",
      i = "DOIs created by the ALA have a prefix of 10.26197/ala."
    )
    abort(bullets, call = error_call)
  }

  path <- atlas_url("doi_download", doi_string = doi_str) |>
          atlas_download(ext = ".zip", cache_file = tempfile(pattern = "data"))

  if(is.null(path)){
    NULL
  }else{
    record_file <- grep("^records", unzip(path, list=TRUE)$Name, 
                        ignore.case=TRUE, value=TRUE)
    df <- read.csv(unz(path, record_file), stringsAsFactors = FALSE)
    attr(df, "doi") <- doi
    return(df)
  }
}


url_download <- function(url){
  local_file <- atlas_download(url, 
    cache_file = tempfile(pattern = "data"), 
    ext = ".zip")
  tryCatch(
    result <- read.csv(unz(local_file, "data.csv"), stringsAsFactors = FALSE),
    error = function(e) {
      bullets <- c(
        "There was a problem reading the occurrence data and it looks like no data were returned."
      )
      inform(bullets)
    }
  )
  
  # rename cols so they match requested cols
  names(result) <- rename_columns(names(result), type = "occurrence")
  
  # replace 'true' and 'false' with boolean
  valid_assertions <- show_all_assertions()$id
  assertions_check <- names(result) %in% valid_assertions
  if(any(assertions_check)){
    result <- fix_assertion_cols(result, names(result)[assertions_check])
  }
  
  return(result)
}