#' Internal function to `collapse()` for `type = "doi"`
#' @importFrom rlang abort
#' @noRd
#' @keywords Internal
collapse_doi <- function(.data, error_call = caller_env()){
  if(is.null(.data$filter)){
    abort("A DOI must be specified using `filter(doi == 'my-doi-here')`", 
          call = error_call)
  }
  
  if(is.null(.data$filter$doi)){
    abort("No doi has been supplied", 
          call = error_call)
  }
  
  if(pour("atlas", "acronym") != "ALA"){
    abort("`collect()` with `type = 'doi'` has only been implemented for ALA", 
          call = error_call)    
  }
  
  doi <- .data$filter$doi[[1]]
  
  # remove "https://" if present
  if (grepl("^http", doi)) {
    doi <- str_remove(doi, "https://doi.org/") # TODO: remove once better solution is found
  }
  
  # extract useful part of DOI
  doi_str <- str_split(doi, "ala.")[[1]][2]
  if (is.na(doi_str)) {
    bullets <- c(
      "DOI has not been generated by the ALA.",
      i = "DOIs created by the ALA have a prefix of 10.26197/ala."
    )
    abort(bullets, call = error_call)
  }
  
  result <- list(
    type = "doi",
    url = url_lookup("doi_download", doi_string = doi_str),
    headers = build_headers(),
    download = TRUE)
  class(result) <- "files_query"
  return(result)
}