#' subset of collect for a doi.
#' @param .data An object of class `data_request`
#' @noRd
#' @keywords Internal
#' @importFrom potions pour
#' @importFrom rlang abort
#' @importFrom rlang inform
#' @importFrom stringr str_remove
#' @importFrom tibble tibble
collect_doi <- function(.data, error_call = caller_env()) {
  
  if(is.null(.data$doi)){
    abort("No doi has been supplied")
  }
  
  if(pour("atlas", "acronym") != "ALA"){
    abort("`collect()` with `type = 'doi'` has only been implemented for ALA")    
  }

  # remove "https://" if present
  if (grepl("^http", doi)) {
    doi <- str_remove(doi, "https://doi.org/") # TODO: remove once better solution is found
  }
  
  # strip useful part of DOI
  doi_str <- str_split(doi, "ala.")[[1]][2]
  if (is.na(doi_str)) {
    bullets <- c(
      "DOI has not been generated by the ALA.",
      i = "DOIs created by the ALA have a prefix of 10.26197/ala."
    )
    abort(bullets, call = error_call)
  }
  
  if(pour("package", "verbose")) {
    cat("Downloading\n")
  }
  
  url_complete <- url_lookup("doi_download", doi_string = doi_str)
  result <- url_download(url_complete, ext = "zip")
  
  if(is.null(result)){
    inform("Download failed")
    return(tibble())
  }else{
    attr(result, "doi") <- doi
    return(result)
  }
}
