#' Build a data request object
#' 
#' @param taxa \code{data.frame}: generated by a call to \code{\link{select_taxa}()}. This
#' argument also accepts a vector of unique species identifiers.
#' @param filters \code{data.frame}: generated by a call to \code{\link{select_filters}()}
#' @param locations \code{string}: generated by a call to \code{\link{select_locations}()}
#' @param columns \code{data.frame}: generated by a call to \code{\link{select_columns}()}
#' @export
data_request <- function(taxa = NULL, filters = NULL, locations = NULL,
                      columns = NULL){
  
  if(!is.null(taxa)) {
    check_taxa_arg(taxa)
  }
  if(!is.null(filters) && !any(grepl("ala_filters", class(filters)))){
    stop("`filters` argument requires an input generated by `select_filters()`")
  }
  if(!is.null(locations) && !any(grepl("ala_locations", class(locations)))){
    stop("`locations` argument requires an input generated by `select_locations()`")
  }
  if(!is.null(columns) && !any(grepl("ala_columns", class(columns)))){
    stop("`columns` argument requires an input generated by `select_columns()`")
  }
  
  request <- structure(list(taxa = taxa, 
                          filters = filters,
                          locations = locations,
                          columns = columns), class = "data_request")
  
  return(request)
}



# new_data_request <- function(x = list){
#   stopifnot(is.list(x))
#   structure(x, class = "")
# }