#' Specify fields for occurrence download
#' 
#' @param ... zero or more individual column names to include
#' @param group \code{string}: (optional) name of one or more column groups to
#' include. Valid options are \code{"basic"}, \code{"event"} and
#' \code{"assertion"}
#' @describeIn galah_select Deprecated function name
#' @export
select_columns <- function(..., group){
  galah_select(..., group = group)
}

#' Choose filters to narrow down occurrence queries
#'
#' @param ... filters, in the form \code{field logical value}
#' @param profile \code{string}: (optional) a data quality profile to apply to the
#' records. See \code{\link{find_profiles}} for valid profiles. By default
#' no profile is applied.
#' @describeIn galah_filter Deprecated function name
#' @export
select_filters <- function(..., profile = NULL) {
  galah_filter(..., profile = profile)
}


#' Build a WKT string from an sf spatial object or verify an existing WKT
#'
#' @param query wkt string or sf object
#' @describeIn galah_location Deprecated function name
#' @export
select_locations <- function(query) {
  galah_location(query)
}

#' Old version of atlas_counts
#'
#' @describeIn atlas_counts Deprecated function name
#' @export
ala_counts <- function(taxa = NULL, filters = NULL, locations = NULL,
                       group_by = NULL, 
                       limit = 100,
                       type = c("record" ,"species"),
                       refresh_cache = FALSE){
  atlas_counts.default(
    taxa = taxa, 
    filter = filters, 
    location = locations,
    group_by = group_by, 
    limit = limit,
    type = type,
    refresh_cache = refresh_cache)
}

#' Old version of atlas_occurrences
#'
#' @param filters \code{data.frame}: DEPRECATED - generated by a call to
#' \code{\link{select_filters}()}
#' @param locations \code{string}: DEPRECATED - generated by a call to
#' \code{\link{select_locations}()}
#' @param columns \code{data.frame}: DEPRECATED - generated by a call to
#' \code{\link{select_columns}()} 
#' @describeIn atlas_occurrences Deprecated function name
#' @export
ala_occurrences <- function(taxa = NULL, filters = NULL, locations = NULL,
                            columns = select_columns(group = "basic"),
                            mint_doi = FALSE, doi, refresh_cache = FALSE) {
  atlas_occurrences(
    taxa = taxa, 
    filter = filters, 
    location = locations,
    select = columns,
    mint_doi = mint_doi, 
    doi = doi, 
    refresh_cache = refresh_cache) 
}

#' Old version of atlas_species
#' 
#' @inheritParams ala_occurrences
#' @param refresh_cache \code{logical}: if set to `TRUE` and 
#' `galah_config(caching = TRUE)` then files cached from a previous query will 
#' be replaced by the current query
#' @describeIn atlas_species Deprecated function name
#' @export
ala_species <- function(taxa = NULL, filters = NULL, locations = NULL,
                        refresh_cache = FALSE) {
  atlas_species(
    taxa = taxa,
    filter = filters,
    location = locations,
    refresh_cache = refresh_cache
  )
}

#' Old version of atlas_taxonomy
#' 
#' @param taxa The identity of the clade for which a taxonomic
#' hierarchy should be returned. Should be specified using an object of class 
#' \code{data.frame} and \code{ala_id}, as returned from
#' \code{\link{select_taxa}()}. 
#' @param down_to \code{string}: A taxonomic rank to search down to. See
#' \code{\link{find_ranks}()} for valid inputs.
#' @describeIn atlas_taxonomy Deprecated function name
#' @export
ala_taxonomy <- function(taxa, down_to){
  atlas_species(
    taxa = taxa,
    down_to = down_to
  )
}

#' Old version of atlas_media
#' 
#' @inheritParams ala_occurrences
#' @param download_dir \code{string}: path to directory to store the downloaded
#' media in
#' @param refresh_cache \code{logical}: if set to `TRUE` and 
#' `galah_config(caching = TRUE)` then files cached from a previous query will 
#' be replaced by the current query
#' @describeIn atlas_media Deprecated function name
#' @export
ala_media <- function(taxa = NULL, 
                      filters = NULL, 
                      locations = NULL,
                      columns = select_columns(group = "basic"),
                      download_dir,
                      refresh_cache = FALSE) {
  atlas_media(
    taxa = taxa,
    filter = filters,
    select = columns,
    download_dir = download_dir,
    refresh_cache = FALSE
  )
}