#' Build a data request object
#' 
#' @param taxa `data.frame`: generated by a call to [search_taxa()]. This
#' argument also accepts a vector of unique species identifiers.
#' @param filter `data.frame`: generated by a call to [select_filters()]
#' @param geolocate `string`: generated by a call to [select_locations()]
#' @param select `data.frame`: generated by a call to [select_columns()]
#' @param ... other function-specific request parameters
#' @export
galah_call <- function(taxa = NULL, 
                       filter = NULL, 
                       select = NULL,
                       geolocate = NULL, 
                       group_by = NULL, 
                       ...){
  
  extra_args <- list(...)
  
  if(!is.null(taxa)) {
    check_taxa_arg(taxa)
  }
  if(!is.null(filter) && !any(grepl("galah_filter", class(filter)))){
    stop("`filter` argument requires an input generated by `galah_filter()`")
  }
  if(!is.null(select) && !any(grepl("galah_select", class(select)))){
    stop("`select` argument requires an input generated by `galah_select()`")
  }
  if(!is.null(geolocate) && !any(grepl("galah_geolocate", class(galah_geolocate)))){
    stop("`geolocate` argument requires an input generated by `galah_geolocate()`")
  }
  if(!is.null(group_by) && !any(grepl("galah_group_by", class(group_by)))){
    stop("`group_by` argument requires an input generated by `galah_group_by()`")
  }
  
  request <- structure(c(list(taxa = taxa,
                              select = select, 
                              filter = filter,
                              geolocate = geolocate,
                              group_by = group_by),
                         extra_args),
                       class = "data_request")
  
  return(request)
}


update_galah_call <- function(data_request, ...){
  dots <- list(...)
  result <- lapply(
    names(data_request), 
    function(a){
      if(any(names(dots) == a)){
        if(is.null(data_request[[a]])){
          dots[[a]]
        }else{
          rbind(data_request[[a]], dots[[a]])
        }
      }else{
        data_request[[a]]
      }
    })
  names(result) <- names(data_request)
  class(result) <- "data_request"
  result
}


#' @rdname galah_call
#' @export
print.data_request <- function(object){
  filled_slots <- !unlist(lapply(object, is.null))
  if(any(filled_slots)){
    cat("An object of type `data_request` containing:\n\n")
    print(as.list(object[filled_slots]))
    cat(paste0("...and ", 5-length(which(filled_slots)), " empty slots"))
  }else{
    cat("An empty object of type `data_request`")
  }
}